name: Deploy
on:
  push:
    branches: gh-pages
  pull_request:
    branches: gh-pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "whole-owl-73"
          entrypoint: "server.ts"
          root: "."
