name: Deploy
on:
  push:
    branches: gh-pages
  pull_request:
    branches: gh-pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "clever-lamb-92"
          entrypoint: "server.ts"
          root: "."
